name: Quarkus Platform Deploy Snapshots

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

env:
  LANG: en_US.UTF-8
jobs:
  build-and-deploy:
    permissions:
      issues: write
      packages: read
    name: "Build and deploy"
    runs-on: ubuntu-latest
    if: github.repository == 'quarkusio/quarkus-platform'
    env:
      MAVEN_OPTS: -Xmx2048m -XX:MaxMetaspaceSize=1000m
    steps:
      - uses: actions/checkout@v5
        with:
          ref: main
      - name: Reclaim Disk Space
        run: .github/ci-prerequisites.sh
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y-%m")" >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache Maven Repository
        id: cache-maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          # refresh cache every month to avoid unlimited growth
          key: deploy-snapshots-${{ steps.get-date.outputs.date }}
      - name: Build and Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_API_TOKEN }}
          SERVER_USERNAME: ${{ secrets.SERVER_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
        run: |
          ./mvnw -B -N versions:set-property -Dproperty=quarkus.version -DnewVersion=999-SNAPSHOT -DenableSnapshotsRepository
          ./mvnw -B -Dsync -DenableSnapshotsRepository
          ./mvnw -e -B --settings .github/mvn-settings.xml \
            -DskipTests -DskipITs \
            -DretryFailedDeploymentCount=10 \
            -DenableSnapshotsRepository \
            clean deploy
      - name: Delete Local Artifacts From Cache
        shell: bash
        run: rm -r ~/.m2/repository/io/quarkus/platform ~/.m2/repository/io/quarkus/quarkus-universe-bom

      - name: Report
        uses: quarkusio/report-status-in-issue@main
        if: always()
        with:
          github-token: ${{ secrets.ECOSYSTEM_CI_TOKEN }}
          status: ${{ job.status }}
          issue-repository: quarkusio/quarkus
          issue-number: 35716
